## Numpy Array Operations


In [3]:
import numpy as np



In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With step", arr[1:8:2])
print("Negative Indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With step [2 4 6 8]
Negative Indexing 8


## 2-D Array Operations

### Slicing


In [11]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("First Row", arr_2d[0, :])
print("First Column", arr_2d[:, 0])
print("Entire Row", arr_2d[1])
print("Entire Column", arr_2d[:, 1])
print("Sub-Matrix", arr_2d[1:, 1:3])

Specific element 6
First Row [1 2 3]
First Column [1 4 7]
Entire Row [4 5 6]
Entire Column [2 5 8]
Sub-Matrix [[5 6]
 [8 9]]


## Sorting


In [16]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted array", np.sort(unsorted))

arr_2d_Unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_Unsorted, axis = 0))
print("Sorted 2D array by column", np.sort(arr_2d_Unsorted, axis = 1))

Sorted array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by column [[1 3]
 [1 2]
 [2 3]]


##  +,-,/,* 

In [2]:
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

#Element wise operations
A + B
A * B
A ** 2
np.sqrt(A)

#Matrix Multiplication- Key for Ml!
A @ B
np.dot(A, B)

#Scalar Operations(Broadcasting)
A * 10
A + 100

#Transpose- flip rows/col
A.T

NameError: name 'np' is not defined

## Filter

In [4]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9 ,10])
even_number = numbers[numbers % 2 == 0]
divisibleby_3 = numbers[numbers % 3 == 0]
print("Even Numbers", even_number)
print("Numbers divisible by 3", divisibleby_3)

Even Numbers [ 2  4  6  8 10]
Numbers divisible by 3 [3 6 9]


## Filter With Mask

In [5]:
mask = numbers > 5
print("Numbers Greater than 5", numbers[mask])

Numbers Greater than 5 [ 6  7  8  9 10]


## Fancy Indexing vs np.where()

In [7]:
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where", numbers[where_result])

[1 3 5]
NP where [ 6  7  8  9 10]


In [8]:
condition_array = np.where(numbers > 5, numbers*4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


In [13]:
arr = np.array([1, 2, 3, 4, 5])
result = np.where(arr > 3, 100, 0)
print(result)

#Replace negatives with zero
neg = np.array([-2, 4, -3, 9, -1])
res = np.where(neg < 0, 0, neg)
print(res)

#USING with Strings
marks = np.array([35, 80, 60, 20])
grade = np.where(marks >= 40, "Pass", "Fail")
print(grade)

D_arr = np.array([[1, 2], [3, 4]])
odd = np.where(D_arr % 2 == 0, "Even", "Odd")
print(odd)



[  0   0   0 100 100]
[0 4 0 9 0]
['Fail' 'Pass' 'Pass' 'Fail']
[['Odd' 'Even']
 ['Odd' 'Even']]


### Adding and Removing data


In [14]:
#Merging the arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)


[1 2 3 4 5 6]


## Array Compatibility

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility Shapes", a.shape == b.shape)




Compatibility Shapes True


In [21]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))  #Vstack always add new row 
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [25]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion", deleted)

Array after deletion [1 2 4 5]
