## Numpy Array And Basics

In [1]:
import numpy as np


### Creating array from list


In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)

1D Array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### List vs Numpy


In [6]:
py_list = [1, 2, 3]
print("Python list Multiplication: ", py_list * 2)

np_array = np.array([1, 2, 3])
print("Python array Multiplication", np_array * 2)

import time

start = time.time()
py_list = [i*2 for i in range (100000)]
print("\n List Operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy Operation time: ", time.time() - start)

Python list Multiplication:  [1, 2, 3, 1, 2, 3]
Python array Multiplication [2 4 6]

 List Operation time:  0.0033142566680908203

 Numpy Operation time:  0.0025899410247802734


## Creating array from scratch


### Special arrays


In [8]:
zeroes = np.zeros((3, 4))
print("Zeroes arry: \n", zeroes)

ones = np.ones((2, 3))
print("Ones array: \n", ones)

identity = np.eye(4)
print("Identity Matrix: \n", identity)

full = np.full((3, 3), 7)
print("Full of 7 array: \n", full)

Zeroes arry: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix: 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Full of 7 array: 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


### Ranges


In [14]:
arrange = np.arange(0, 20, 5)    #20 is non inclusive outer boundary
print(f"Counting from 0 to twenty with multiples of 5: {arrange} ")

divide = np.linspace(0, 1, 5)
print(f"Divide 0 to 1 in 5 parts: {divide}")

Counting from 0 to twenty with multiples of 5: [ 0  5 10 15] 
Divide 0 to 1 in 5 parts: [0.   0.25 0.5  0.75 1.  ]


## Random (Essentials in ML)

In [ ]:
random = np.random.random((2,3))
print(f"random array: \n {random}")

see = np.random.seed(42)
print(see)

#Create random array of 10 elements

elements = np.random.randn(10)
print(elements)

#create 4*4 random matrix
matrix = np.random.randint(1, 20, (4, 4))
print(matrix)

#Shuffle an array
element = np.array([1, 2, 4, 5, 6])
np.random.shuffle(element)
print(element)

#Pick 3 Random Numbers
np.random.choice(element, 3)

random array: 
 [[0.56328822 0.3854165  0.01596625]
 [0.23089383 0.24102547 0.68326352]]
None
[ 0.49671415 -0.1382643   0.64768854  1.52302986 -0.23415337 -0.23413696
  1.57921282  0.76743473 -0.46947439  0.54256004]
[[ 1 12 12 17]
 [10 16 15 15]
 [19 12  3  5]
 [19  7  9  7]]
[4 6 1 5 2]


array([6, 6, 4])